name: "尝试使用actions做CI"
run-name: "自动化测试集成"
on: [push]
jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - name: "从仓库克隆代码"
        uses: actions/checkout@v5

      - name: "显示当前python版本"
        run: python -c "import sys; print(sys.version)"

      - name: "测试运行main.py"
        run: python main.py